/**
 * Shell completion generators for ntfy-cli.
 *
 * Generates bash, zsh, and fish completion scripts that are dynamically
 * populated with profile names and topic names from the current config.
 */

import type { Config } from "./config.js";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Collect all profile names from the config (empty array if no config).
 */
function profileNames(config: Config | null): string[] {
  if (!config) return [];
  return Object.keys(config.profiles);
}

/**
 * Collect all unique topic names across all profiles.
 */
function allTopicNames(config: Config | null): string[] {
  if (!config) return [];
  const topics = new Set<string>();
  for (const profile of Object.values(config.profiles)) {
    for (const t of profile.topics) {
      topics.add(t);
    }
  }
  return Array.from(topics);
}

// ---------------------------------------------------------------------------
// Top-level commands and flags (kept in one place to stay DRY)
// ---------------------------------------------------------------------------

const TOP_LEVEL_COMMANDS = [
  "messages",
  "msg",
  "all",
  "unread",
  "send",
  "read",
  "delete",
  "health",
  "version",
  "topics",
  "config",
  "completions",
  "watch",
];

const GLOBAL_FLAGS = [
  "--server",
  "--json",
  "--no-color",
  "--quiet",
  "--help",
];

// ---------------------------------------------------------------------------
// Bash completions
// ---------------------------------------------------------------------------

/**
 * Generate a bash completion script for ntfy.
 *
 * Install with:
 *   ntfy completions bash >> ~/.bash_completion
 *   # or
 *   ntfy completions bash > /etc/bash_completion.d/ntfy
 */
export function generateBashCompletions(config: Config | null): string {
  const profiles = profileNames(config);
  const topics = allTopicNames(config);

  const profilesStr = profiles.join(" ");
  const topicsStr = topics.join(" ");

  return `# ntfy-cli bash completion
# Generated by: ntfy completions bash
# Install: source this file or add to ~/.bash_completion

_ntfy_completions() {
    local cur prev words cword
    _init_completion 2>/dev/null || {
        COMPREPLY=()
        cur="\${COMP_WORDS[COMP_CWORD]}"
        prev="\${COMP_WORDS[COMP_CWORD-1]}"
        words=("\${COMP_WORDS[@]}")
        cword="\${COMP_CWORD}"
    }

    local commands="${TOP_LEVEL_COMMANDS.join(" ")}"
    local global_flags="${GLOBAL_FLAGS.join(" ")}"
    local profiles="${profilesStr}"
    local topics="${topicsStr}"

    # Handle flag arguments that consume a value
    case "\${prev}" in
        --server)
            COMPREPLY=( \$(compgen -W "\${profiles}" -- "\${cur}") )
            return 0
            ;;
        --topic|-t)
            COMPREPLY=( \$(compgen -W "\${topics}" -- "\${cur}") )
            return 0
            ;;
        --priority|-p)
            COMPREPLY=( \$(compgen -W "1 2 3 4 5 min low default high urgent max" -- "\${cur}") )
            return 0
            ;;
        --since|-s)
            COMPREPLY=( \$(compgen -W "1h 6h 12h 24h 2d 7d all" -- "\${cur}") )
            return 0
            ;;
        --delay)
            COMPREPLY=( \$(compgen -W "30s 1m 5m 30m 1h 3h 12h" -- "\${cur}") )
            return 0
            ;;
        --title|--tags|--click|--attach|--limit|--device|--interval|--group|--sound)
            # Free-form value; no completion
            return 0
            ;;
    esac

    # Find the command word (first non-flag positional)
    local cmd=""
    local i
    for (( i=1; i<cword; i++ )); do
        if [[ "\${words[i]}" != -* ]]; then
            cmd="\${words[i]}"
            break
        fi
    done

    case "\${cmd}" in
        messages|msg)
            COMPREPLY=( \$(compgen -W "--topic -t --since -s --priority --limit --json --no-color --quiet" -- "\${cur}") )
            ;;
        unread)
            COMPREPLY=( \$(compgen -W "--topic --since --json --count --total --no-color --quiet" -- "\${cur}") )
            ;;
        send)
            COMPREPLY=( \$(compgen -W "--topic -t --title --priority -p --tags --delay --click --attach --markdown --md --json --quiet" -- "\${cur}") )
            ;;
        read)
            COMPREPLY=( \$(compgen -W "--topic --all --quiet" -- "\${cur}") )
            ;;
        delete)
            COMPREPLY=( \$(compgen -W "--topic -t --quiet" -- "\${cur}") )
            ;;
        health)
            COMPREPLY=( \$(compgen -W "--json --all --quiet" -- "\${cur}") )
            ;;
        watch)
            COMPREPLY=( \$(compgen -W "--topic -t --group --interval --priority --no-sound --sound --device --quiet" -- "\${cur}") )
            ;;
        topics)
            # Find sub-command
            local sub=""
            for (( i=2; i<cword; i++ )); do
                if [[ "\${words[i]}" != -* ]]; then
                    sub="\${words[i]}"
                    break
                fi
            done
            case "\${sub}" in
                list|ls)
                    COMPREPLY=( \$(compgen -W "--json --quiet" -- "\${cur}") )
                    ;;
                add)
                    # Suggest known topics for convenience
                    COMPREPLY=( \$(compgen -W "\${topics}" -- "\${cur}") )
                    ;;
                remove|rm)
                    COMPREPLY=( \$(compgen -W "\${topics}" -- "\${cur}") )
                    ;;
                group)
                    COMPREPLY=( \$(compgen -W "add remove" -- "\${cur}") )
                    ;;
                *)
                    COMPREPLY=( \$(compgen -W "list ls add remove rm group" -- "\${cur}") )
                    ;;
            esac
            ;;
        config)
            local sub=""
            for (( i=2; i<cword; i++ )); do
                if [[ "\${words[i]}" != -* ]]; then
                    sub="\${words[i]}"
                    break
                fi
            done
            case "\${sub}" in
                add)
                    COMPREPLY=( \$(compgen -W "--url --user --password --topic" -- "\${cur}") )
                    ;;
                remove|rm)
                    COMPREPLY=( \$(compgen -W "\${profiles}" -- "\${cur}") )
                    ;;
                use)
                    COMPREPLY=( \$(compgen -W "\${profiles}" -- "\${cur}") )
                    ;;
                list|ls|show)
                    COMPREPLY=( \$(compgen -W "--json" -- "\${cur}") )
                    ;;
                *)
                    COMPREPLY=( \$(compgen -W "add remove rm list ls use show" -- "\${cur}") )
                    ;;
            esac
            ;;
        completions)
            COMPREPLY=( \$(compgen -W "bash zsh fish" -- "\${cur}") )
            ;;
        "")
            # No command yet: offer commands and global flags
            COMPREPLY=( \$(compgen -W "\${commands} \${global_flags}" -- "\${cur}") )
            ;;
        *)
            COMPREPLY=( \$(compgen -W "\${global_flags}" -- "\${cur}") )
            ;;
    esac
}

complete -F _ntfy_completions ntfy
`;
}

// ---------------------------------------------------------------------------
// Zsh completions
// ---------------------------------------------------------------------------

/**
 * Generate a zsh completion function (_ntfy) for ntfy.
 *
 * Install with:
 *   ntfy completions zsh > "${fpath[1]}/_ntfy"
 *   # then restart zsh or run: autoload -U compinit && compinit
 */
export function generateZshCompletions(config: Config | null): string {
  const profiles = profileNames(config);
  const topics = allTopicNames(config);

  const profilesZsh = profiles.map((p) => `'${p}'`).join(" ");
  const topicsZsh = topics.map((t) => `'${t}'`).join(" ");

  return `#compdef ntfy
# ntfy-cli zsh completion
# Generated by: ntfy completions zsh
# Install: ntfy completions zsh > "\${fpath[1]}/_ntfy"

_ntfy() {
    local -a commands profiles topics

    commands=(
        'messages:Fetch and display messages for a topic'
        'msg:Alias for messages'
        'all:Fetch messages for the default/FAST-all topic'
        'unread:Show unread messages across watched topics'
        'send:Send a notification message'
        'read:Mark topic(s) as read'
        'delete:Delete a message by ID'
        'health:Check server health and version'
        'version:Print the ntfy-cli version'
        'topics:Manage watched topics'
        'config:Manage server profiles'
        'completions:Generate shell completion scripts'
        'watch:Watch topics for new messages in real time'
    )

    profiles=(${profilesZsh || "# (no profiles configured)"})
    topics=(${topicsZsh || "# (no topics configured)"})

    local -a global_opts
    global_opts=(
        '--server[Use a specific server profile]:profile:(${profilesZsh})'
        '--json[Output raw JSON]'
        '--no-color[Disable colored output]'
        '--quiet[Suppress non-essential output]'
        '(-h --help)'{-h,--help}'[Show help text]'
    )

    local state line
    typeset -A opt_args

    _arguments -C \\
        \${global_opts[@]} \\
        ':command:->command' \\
        '*::args:->args' && return 0

    case \$state in
        command)
            _describe 'ntfy command' commands
            ;;
        args)
            case \$line[1] in
                messages|msg|all)
                    _arguments \\
                        '(-t --topic)'{-t,--topic}'[Topic name]:topic:(${topicsZsh})' \\
                        '(-s --since)'{-s,--since}'[Lookback period]:since:(1h 6h 12h 24h 2d 7d all)' \\
                        '--priority[Minimum priority filter]:priority:(1 2 3 4 5 min low default high urgent max)' \\
                        '--limit[Maximum messages to show]:count:' \\
                        '--json[Output raw JSON]' \\
                        '--no-color[Disable colored output]' \\
                        '--quiet[Suppress non-essential output]'
                    ;;
                unread)
                    _arguments \\
                        '--topic[Filter to single topic]:topic:(${topicsZsh})' \\
                        '--since[Lookback period]:since:(1h 6h 12h 24h 2d 7d all)' \\
                        '--json[Output raw JSON]' \\
                        '--count[Print unread count as integer]' \\
                        '--total[Print total count across all topics]' \\
                        '--no-color[Disable colored output]' \\
                        '--quiet[Suppress non-essential output]'
                    ;;
                send)
                    _arguments \\
                        '*:message text:' \\
                        '(-t --topic)'{-t,--topic}'[Topic name]:topic:(${topicsZsh})' \\
                        '--title[Notification title]:title:' \\
                        '(-p --priority)'{-p,--priority}'[Priority level]:priority:(1 2 3 4 5 min low default high urgent max)' \\
                        '--tags[Comma-separated tags]:tags:' \\
                        '--delay[Schedule delivery delay]:delay:(30s 1m 5m 30m 1h 3h 12h)' \\
                        '--click[URL to open on notification click]:url:_urls' \\
                        '--attach[URL of attachment]:url:_urls' \\
                        '(--markdown --md)--markdown[Render message as Markdown]' \\
                        '(--markdown --md)--md[Render message as Markdown]' \\
                        '--json[Output raw JSON]' \\
                        '--quiet[Suppress non-essential output]'
                    ;;
                read)
                    _arguments \\
                        '--topic[Mark specific topic as read]:topic:(${topicsZsh})' \\
                        '--all[Mark all topics on all profiles as read]' \\
                        '--quiet[Suppress non-essential output]'
                    ;;
                delete)
                    _arguments \\
                        ':message ID:' \\
                        '(-t --topic)'{-t,--topic}'[Topic (optional)]:topic:(${topicsZsh})' \\
                        '--quiet[Suppress non-essential output]'
                    ;;
                health)
                    _arguments \\
                        '--json[Output raw JSON]' \\
                        '--all[Check all profiles]' \\
                        '--quiet[Suppress non-essential output]'
                    ;;
                watch)
                    _arguments \\
                        '(-t --topic)'{-t,--topic}'[Topic name]:topic:(${topicsZsh})' \\
                        '--group[Topic group name]:group:' \\
                        '--interval[Polling interval in seconds]:seconds:' \\
                        '--priority[Minimum priority for audio]:priority:(1 2 3 4 5 min low default high urgent max)' \\
                        '--no-sound[Disable audio notifications]' \\
                        '--sound[Path to custom sound file]:path:_files' \\
                        '--device[Audio device for afplay]:device:' \\
                        '--quiet[Suppress non-essential output]'
                    ;;
                completions)
                    _arguments ':shell:(bash zsh fish)'
                    ;;
                topics)
                    local -a topic_cmds
                    topic_cmds=(
                        'list:List watched topics and groups'
                        'ls:Alias for list'
                        'add:Add a topic to the watch list'
                        'remove:Remove a topic from the watch list'
                        'rm:Alias for remove'
                        'group:Manage topic groups'
                    )
                    _arguments -C \\
                        ':subcommand:->sub' \\
                        '*::subargs:->subargs' && return 0
                    case \$state in
                        sub)
                            _describe 'topics subcommand' topic_cmds
                            ;;
                        subargs)
                            case \$line[1] in
                                list|ls)
                                    _arguments '--json[Output raw JSON]'
                                    ;;
                                add)
                                    _arguments ':topic name:'
                                    ;;
                                remove|rm)
                                    _arguments ':topic name:(${topicsZsh})'
                                    ;;
                                group)
                                    _arguments ':action:(add remove)'
                                    ;;
                            esac
                            ;;
                    esac
                    ;;
                config)
                    local -a config_cmds
                    config_cmds=(
                        'add:Add a new server profile'
                        'remove:Remove a server profile'
                        'rm:Alias for remove'
                        'list:List all configured profiles'
                        'ls:Alias for list'
                        'use:Set the active profile'
                        'show:Show the active profile details'
                    )
                    _arguments -C \\
                        ':subcommand:->sub' \\
                        '*::subargs:->subargs' && return 0
                    case \$state in
                        sub)
                            _describe 'config subcommand' config_cmds
                            ;;
                        subargs)
                            case \$line[1] in
                                add)
                                    _arguments \\
                                        ':profile name:' \\
                                        '--url[Server URL]:url:_urls' \\
                                        '--user[Username]:user:' \\
                                        '--password[Password]:password:' \\
                                        '--topic[Default topic]:topic:'
                                    ;;
                                remove|rm)
                                    _arguments ':profile name:(${profilesZsh})'
                                    ;;
                                use)
                                    _arguments ':profile name:(${profilesZsh})'
                                    ;;
                                list|ls|show)
                                    _arguments '--json[Output raw JSON]'
                                    ;;
                            esac
                            ;;
                    esac
                    ;;
            esac
            ;;
    esac
}

_ntfy "\$@"
`;
}

// ---------------------------------------------------------------------------
// Fish completions
// ---------------------------------------------------------------------------

/**
 * Generate fish shell completions for ntfy.
 *
 * Install with:
 *   ntfy completions fish > ~/.config/fish/completions/ntfy.fish
 */
export function generateFishCompletions(config: Config | null): string {
  const profiles = profileNames(config);
  const topics = allTopicNames(config);

  // Fish uses tab-separated "value\tdescription" pairs
  const profileList = profiles.join(" ");
  const topicList = topics.join(" ");

  return `# ntfy-cli fish completion
# Generated by: ntfy completions fish
# Install: ntfy completions fish > ~/.config/fish/completions/ntfy.fish

# Disable file completion by default
complete -c ntfy -f

# ---------------------------------------------------------------------------
# Helper: detect subcommand in use
# ---------------------------------------------------------------------------
function __ntfy_using_command
    set -l cmd (commandline -opc)
    if test (count $cmd) -gt 1
        # Return the first non-flag positional after 'ntfy'
        for token in $cmd[2..]
            if not string match -q -- '-*' $token
                echo $token
                return
            end
        end
    end
end

function __ntfy_using_subcommand
    set -l cmd (commandline -opc)
    set -l count 0
    for token in $cmd[2..]
        if not string match -q -- '-*' $token
            set count (math $count + 1)
            if test $count -eq 2
                echo $token
                return
            end
        end
    end
end

# ---------------------------------------------------------------------------
# Top-level commands
# ---------------------------------------------------------------------------
complete -c ntfy -n 'not __ntfy_using_command' -a 'messages'    -d 'Fetch and display messages for a topic'
complete -c ntfy -n 'not __ntfy_using_command' -a 'msg'         -d 'Alias for messages'
complete -c ntfy -n 'not __ntfy_using_command' -a 'all'         -d 'Fetch messages for default/FAST-all topic'
complete -c ntfy -n 'not __ntfy_using_command' -a 'unread'      -d 'Show unread messages across watched topics'
complete -c ntfy -n 'not __ntfy_using_command' -a 'send'        -d 'Send a notification message'
complete -c ntfy -n 'not __ntfy_using_command' -a 'read'        -d 'Mark topic(s) as read'
complete -c ntfy -n 'not __ntfy_using_command' -a 'delete'      -d 'Delete a message by ID'
complete -c ntfy -n 'not __ntfy_using_command' -a 'health'      -d 'Check server health and version'
complete -c ntfy -n 'not __ntfy_using_command' -a 'version'     -d 'Print the ntfy-cli version'
complete -c ntfy -n 'not __ntfy_using_command' -a 'topics'      -d 'Manage watched topics'
complete -c ntfy -n 'not __ntfy_using_command' -a 'config'      -d 'Manage server profiles'
complete -c ntfy -n 'not __ntfy_using_command' -a 'completions' -d 'Generate shell completion scripts'
complete -c ntfy -n 'not __ntfy_using_command' -a 'watch'       -d 'Watch topics for new messages in real time'

# ---------------------------------------------------------------------------
# Global flags (available on all commands)
# ---------------------------------------------------------------------------
complete -c ntfy -l server    -d 'Use a specific server profile' -a '${profileList}'
complete -c ntfy -l json      -d 'Output raw JSON'
complete -c ntfy -l no-color  -d 'Disable colored output'
complete -c ntfy -l quiet     -d 'Suppress non-essential output' -s q
complete -c ntfy -l help      -d 'Show help text'               -s h

# ---------------------------------------------------------------------------
# messages / msg / all
# ---------------------------------------------------------------------------
complete -c ntfy -n '__ntfy_using_command messages; or __ntfy_using_command msg; or __ntfy_using_command all' \\
    -l topic -s t -d 'Topic name' -a '${topicList}'
complete -c ntfy -n '__ntfy_using_command messages; or __ntfy_using_command msg; or __ntfy_using_command all' \\
    -l since -s s -d 'Lookback period' -a '1h 6h 12h 24h 2d 7d all'
complete -c ntfy -n '__ntfy_using_command messages; or __ntfy_using_command msg; or __ntfy_using_command all' \\
    -l priority -d 'Minimum priority filter' -a '1 2 3 4 5 min low default high urgent max'
complete -c ntfy -n '__ntfy_using_command messages; or __ntfy_using_command msg; or __ntfy_using_command all' \\
    -l limit -d 'Maximum messages to show'

# ---------------------------------------------------------------------------
# unread
# ---------------------------------------------------------------------------
complete -c ntfy -n '__ntfy_using_command unread' -l topic  -d 'Filter to single topic' -a '${topicList}'
complete -c ntfy -n '__ntfy_using_command unread' -l since  -d 'Lookback period' -a '1h 6h 12h 24h 2d 7d all'
complete -c ntfy -n '__ntfy_using_command unread' -l count  -d 'Print unread count as integer'
complete -c ntfy -n '__ntfy_using_command unread' -l total  -d 'Print total count across all topics'

# ---------------------------------------------------------------------------
# send
# ---------------------------------------------------------------------------
complete -c ntfy -n '__ntfy_using_command send' -l topic    -s t -d 'Topic name' -a '${topicList}'
complete -c ntfy -n '__ntfy_using_command send' -l title    -d 'Notification title'
complete -c ntfy -n '__ntfy_using_command send' -l priority -s p -d 'Priority level' -a '1 2 3 4 5 min low default high urgent max'
complete -c ntfy -n '__ntfy_using_command send' -l tags     -d 'Comma-separated tags'
complete -c ntfy -n '__ntfy_using_command send' -l delay    -d 'Schedule delivery delay' -a '30s 1m 5m 30m 1h 3h 12h'
complete -c ntfy -n '__ntfy_using_command send' -l click    -d 'URL to open on notification click'
complete -c ntfy -n '__ntfy_using_command send' -l attach   -d 'URL of attachment'
complete -c ntfy -n '__ntfy_using_command send' -l markdown -d 'Render message as Markdown'
complete -c ntfy -n '__ntfy_using_command send' -l md       -d 'Render message as Markdown (alias)'

# ---------------------------------------------------------------------------
# read
# ---------------------------------------------------------------------------
complete -c ntfy -n '__ntfy_using_command read' -l topic -d 'Mark specific topic as read' -a '${topicList}'
complete -c ntfy -n '__ntfy_using_command read' -l all   -d 'Mark all topics on all profiles as read'

# ---------------------------------------------------------------------------
# delete
# ---------------------------------------------------------------------------
complete -c ntfy -n '__ntfy_using_command delete' -l topic -s t -d 'Topic (optional)' -a '${topicList}'

# ---------------------------------------------------------------------------
# health
# ---------------------------------------------------------------------------
complete -c ntfy -n '__ntfy_using_command health' -l all -d 'Check all profiles'

# ---------------------------------------------------------------------------
# watch
# ---------------------------------------------------------------------------
complete -c ntfy -n '__ntfy_using_command watch' -l topic    -s t -d 'Topic name' -a '${topicList}'
complete -c ntfy -n '__ntfy_using_command watch' -l group    -d 'Topic group name'
complete -c ntfy -n '__ntfy_using_command watch' -l interval -d 'Polling interval in seconds'
complete -c ntfy -n '__ntfy_using_command watch' -l priority -d 'Minimum priority for audio' -a '1 2 3 4 5 min low default high urgent max'
complete -c ntfy -n '__ntfy_using_command watch' -l no-sound -d 'Disable audio notifications'
complete -c ntfy -n '__ntfy_using_command watch' -l sound    -d 'Path to custom sound file'
complete -c ntfy -n '__ntfy_using_command watch' -l device   -d 'Audio device for afplay'

# ---------------------------------------------------------------------------
# completions subcommand
# ---------------------------------------------------------------------------
complete -c ntfy -n '__ntfy_using_command completions' -a 'bash zsh fish' -d 'Shell type'

# ---------------------------------------------------------------------------
# topics subcommands
# ---------------------------------------------------------------------------
complete -c ntfy -n '__ntfy_using_command topics; and not __ntfy_using_subcommand' \\
    -a 'list ls add remove rm group' -d 'topics subcommand'

complete -c ntfy -n '__ntfy_using_command topics; and __ntfy_using_subcommand | string match -rq "^(remove|rm)$"' \\
    -a '${topicList}' -d 'Topic to remove'

complete -c ntfy -n '__ntfy_using_command topics; and __ntfy_using_subcommand | string match -rq "^list$"' \\
    -l json -d 'Output raw JSON'

complete -c ntfy -n '__ntfy_using_command topics; and __ntfy_using_subcommand | string match -rq "^group$"' \\
    -a 'add remove' -d 'group subcommand'

# ---------------------------------------------------------------------------
# config subcommands
# ---------------------------------------------------------------------------
complete -c ntfy -n '__ntfy_using_command config; and not __ntfy_using_subcommand' \\
    -a 'add remove rm list ls use show' -d 'config subcommand'

complete -c ntfy -n '__ntfy_using_command config; and __ntfy_using_subcommand | string match -rq "^add$"' \\
    -l url      -d 'Server URL'
complete -c ntfy -n '__ntfy_using_command config; and __ntfy_using_subcommand | string match -rq "^add$"' \\
    -l user     -d 'Username'
complete -c ntfy -n '__ntfy_using_command config; and __ntfy_using_subcommand | string match -rq "^add$"' \\
    -l password -d 'Password'
complete -c ntfy -n '__ntfy_using_command config; and __ntfy_using_subcommand | string match -rq "^add$"' \\
    -l topic    -d 'Default topic'

complete -c ntfy -n '__ntfy_using_command config; and __ntfy_using_subcommand | string match -rq "^(remove|rm|use)$"' \\
    -a '${profileList}' -d 'Profile name'

complete -c ntfy -n '__ntfy_using_command config; and __ntfy_using_subcommand | string match -rq "^(list|ls|show)$"' \\
    -l json -d 'Output raw JSON'
`;
}
